# This file was generated by GoReleaser. DO NOT EDIT.
cask "aictx" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "295ff620bc7dc692a51b9a63daf2f6112bc6bc500b7dbd1e78a21d23480be507"
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8e60d2c974b641dce8e9393625d4c681385fbfcac2c190c36bc006d0beec664"
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0b033cc85c44708985c2b9da8948d01b33ba951814d0aac7fbf95580dff9c47"
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "392a8934565a88d0c52246d14016d28751e13cec54ba920ed0bd1c1589ae92c0"
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aictx"
  desc "Context switcher for AI tool configurations, inspired by kubectx."
  homepage "https://github.com/IQNeoXen/aictx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aictx"

  # No zap stanza required

end
