# This file was generated by GoReleaser. DO NOT EDIT.
cask "aictx" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_darwin_amd64.tar.gz"
      sha256 "b024a623f62e126bc90b42f220eb4d53687c239e3f2d9c7dc1714b8c9b45338b"
    end
    on_arm do
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_darwin_arm64.tar.gz"
      sha256 "5a6fe81c6fbb07d81c20def4681446ad111d62b1c62cdabe710fc440469595ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_linux_amd64.tar.gz"
      sha256 "cf6f7b3a04bd97801e4f7c96182c15b6dc1b7ac407eca6ccffbcd61e10c1b137"
    end
    on_arm do
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_linux_arm64.tar.gz"
      sha256 "8ea222b1c0c8efef4a8524b10615ebfb3ff3814daaf2db4b0474056737a32c8e"
    end
  end

  name "aictx"
  desc "Context switcher for AI tool configurations, inspired by kubectx."
  homepage "https://github.com/IQNeoXen/aictx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aictx"

  # No zap stanza required

end
