# This file was generated by GoReleaser. DO NOT EDIT.
cask "aictx" do
  name "aictx"
  desc "Context switcher for AI tool configurations, inspired by kubectx."
  homepage "https://github.com/IQNeoXen/aictx"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aictx"

  on_macos do
    on_intel do
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_darwin_amd64.tar.gz"
      sha256 "f399954e5ff67a1e3e0f32f8d2cd120b40e47e398b8715064f338ecd1c3b7256"
    end
    on_arm do
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_darwin_arm64.tar.gz"
      sha256 "9f1ea7ddaa41abc88a4bd8e85bb0eacb5c123ffb7ac98112a16c010dec665938"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_linux_amd64.tar.gz"
      sha256 "82fa38b24f26b02f22bef114b89ae0f3932d31b2aecc83798a81147b41844335"
    end
    on_arm do
      url "https://github.com/IQNeoXen/aictx/releases/download/v#{version}/aictx_#{version}_linux_arm64.tar.gz"
      sha256 "61161a95fa436e342a26063131cbe9bd1ece559e1c6bd38f7bb3e45386fc78a7"
    end
  end

  # No zap stanza required
end
